client_config_backend: settings
client_config_file: client_secrets.json
client_config:
  client_id: 13912477904-sbfpg13v959nao81hgktvs3tjr6fvuf5.apps.googleusercontent.com
  client_secret: ki_r65sD3fJ7cvgWsChAwdI9

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install